model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
num_classes: 4
lr: 2e-5
weight_decay: 0.01
epochs: 10

batch_size: 16
max_len: 128
val_split: 0.1
num_workers: 4
seed: 42
data_file: ${base.classifier_file}

accelerator: gpu
devices: 1
precision: 32
grad_clip: 1.0
accum_grad: 1

model_dir: models

logger: mlflow
experiment_name: answer_grader
run_name: run_001
tracking_uri: sqlite:///mlruns.db
log_model: true
