model_name: cross-encoder/ms-marco-MiniLM-L-6-v2 # cross-encoder/ms-marco-TinyBERT-L2-v2
num_classes: 4
lr: 2e-5
weight_decay: 0.01
epochs: 7

batch_size: 16
max_len: 128
val_split: 0.1
num_workers: 4
seed: 42
data_file: ${base.classifier_file}

accelerator: gpu
devices: 1
precision: 32
grad_clip: 1.0
accum_grad: 1

model_dir: models

use_ref_answers: false

logger: mlflow
experiment_name: answer_grader
run_name: cl_marco
log_model: true
