model_name: facebook/bart-base # google/flan-t5-small
lr: 1e-4
weight_decay: 0.01
epochs: 7

batch_size: 32
max_in: 64
max_out: 64
num_workers: 4
val_split: 0.1
seed: 42

use_context: true

accelerator: gpu
devices: 1
precision: 32
grad_clip: 1.0
accum_grad: 1

temperature: 0.3
top_p: 0.9
max_tokens: 128

model_dir: models

logger: mlflow
experiment_name: qa_generator
run_name: qa_bart_context
log_model: true

